/**
BSD 3-Clause License

This file is part of the Basalt project.
https://gitlab.com/VladyslavUsenko/basalt.git

Copyright (c) 2019, Vladyslav Usenko and Nikolaus Demmel.
All rights reserved.
*/
#pragma once

#include <fstream>
#include <string>

#include <yaml-cpp/yaml.h>

#include <basalt/calibration/calibration.hpp>
#include <basalt/camera/generic_camera.hpp>

namespace basalt {

/// Write a Calibration<double> to a human-readable YAML file whose structure
/// matches the loadCalibrationFromYAML() reader in visual_odometer_node.cpp.
///
/// Both JSON (calibration.json via cereal) and this YAML file are written by
/// the calibration tools so that the two-step pipeline (basalt_calibrate →
/// basalt_calibrate_imu) still works via the JSON, while the user gets an
/// annotated YAML ready to pass to --calib_path.
///
/// Note: the `vignette` field is JSON-only — it holds photometric B-spline
/// data that is never read by the VIO runtime.
inline void saveCalibToYAML(const std::string& path,
                            const Calibration<double>& calib) {
  YAML::Emitter out;
  out.SetDoublePrecision(17);  // round-trip safe double precision

  out << YAML::Comment(
      "basalt calibration — generated by basalt_calibrate / basalt_calibrate_imu\n"
      "Load with: ros2 run basalt_ros2 visual_odometry_node "
      "--ros-args -p calib_path:=<this file>");
  out << YAML::Newline;

  out << YAML::BeginMap;

  // ── T_imu_cam ────────────────────────────────────────────────────────────
  out << YAML::Comment(
      "IMU-to-camera extrinsic transforms (one per camera)\n"
      "translation: px/py/pz metres; rotation: quaternion qx/qy/qz/qw");
  out << YAML::Key << "T_imu_cam" << YAML::Value;
  out << YAML::BeginSeq;
  for (const auto& T : calib.T_i_c) {
    const Eigen::Vector3d& t = T.translation();
    const Eigen::Quaterniond q = T.unit_quaternion();
    out << YAML::BeginMap;
    out << YAML::Key << "px" << YAML::Value << t.x();
    out << YAML::Key << "py" << YAML::Value << t.y();
    out << YAML::Key << "pz" << YAML::Value << t.z();
    out << YAML::Key << "qx" << YAML::Value << q.x();
    out << YAML::Key << "qy" << YAML::Value << q.y();
    out << YAML::Key << "qz" << YAML::Value << q.z();
    out << YAML::Key << "qw" << YAML::Value << q.w();
    out << YAML::EndMap;
  }
  out << YAML::EndSeq;

  // ── intrinsics ────────────────────────────────────────────────────────────
  out << YAML::Newline;
  out << YAML::Comment(
      "Camera intrinsics (one per camera, same order as T_imu_cam)");
  out << YAML::Key << "intrinsics" << YAML::Value;
  out << YAML::BeginSeq;
  for (const auto& cam : calib.intrinsics) {
    const std::string type = cam.getName();
    const auto params = cam.getParam();

    out << YAML::BeginMap;
    out << YAML::Key << "camera_type" << YAML::Value << type;
    out << YAML::Key << "intrinsics" << YAML::Value << YAML::BeginMap;

    if (type == "pinhole-radtan8" && params.size() >= 12) {
      out << YAML::Key << "fx" << YAML::Value << params[0];
      out << YAML::Key << "fy" << YAML::Value << params[1];
      out << YAML::Key << "cx" << YAML::Value << params[2];
      out << YAML::Key << "cy" << YAML::Value << params[3];
      out << YAML::Key << "k1" << YAML::Value << params[4];
      out << YAML::Key << "k2" << YAML::Value << params[5];
      out << YAML::Key << "p1" << YAML::Value << params[6];
      out << YAML::Key << "p2" << YAML::Value << params[7];
      out << YAML::Key << "k3" << YAML::Value << params[8];
      out << YAML::Key << "k4" << YAML::Value << params[9];
      out << YAML::Key << "k5" << YAML::Value << params[10];
      out << YAML::Key << "k6" << YAML::Value << params[11];
    } else if (type == "pinhole" && params.size() >= 4) {
      out << YAML::Key << "fx" << YAML::Value << params[0];
      out << YAML::Key << "fy" << YAML::Value << params[1];
      out << YAML::Key << "cx" << YAML::Value << params[2];
      out << YAML::Key << "cy" << YAML::Value << params[3];
    } else {
      // Fallback: write raw parameter array — update loadCalibrationFromYAML()
      // if you need to reload this camera type from YAML.
      out << YAML::Key << "raw_params" << YAML::Value << YAML::BeginSeq;
      for (int i = 0; i < params.size(); ++i) out << params[i];
      out << YAML::EndSeq;
    }

    out << YAML::EndMap;  // intrinsics map
    out << YAML::EndMap;  // camera entry
  }
  out << YAML::EndSeq;

  // ── resolution ────────────────────────────────────────────────────────────
  out << YAML::Newline;
  out << YAML::Comment("Image resolution [width, height] for each camera");
  out << YAML::Key << "resolution" << YAML::Value;
  out << YAML::BeginSeq;
  for (const auto& res : calib.resolution) {
    out << YAML::Flow << YAML::BeginSeq << res.x() << res.y() << YAML::EndSeq;
  }
  out << YAML::EndSeq;

  // ── IMU parameters ────────────────────────────────────────────────────────
  out << YAML::Newline;
  out << YAML::Comment("IMU sampling rate (Hz)");
  out << YAML::Key << "imu_update_rate" << YAML::Value << calib.imu_update_rate;

  // calib_accel_bias (9 coefficients)
  out << YAML::Newline;
  out << YAML::Comment(
      "Accelerometer intrinsic calibration (9 coefficients: "
      "bias + scale/cross-axis terms)");
  out << YAML::Key << "calib_accel_bias" << YAML::Value;
  out << YAML::BeginSeq;
  const auto& accel_bias = calib.calib_accel_bias.getParam();
  for (int i = 0; i < accel_bias.size(); ++i) out << accel_bias[i];
  out << YAML::EndSeq;

  // calib_gyro_bias (12 coefficients)
  out << YAML::Newline;
  out << YAML::Comment(
      "Gyroscope intrinsic calibration (12 coefficients: "
      "bias + scale/cross-axis terms)");
  out << YAML::Key << "calib_gyro_bias" << YAML::Value;
  out << YAML::BeginSeq;
  const auto& gyro_bias = calib.calib_gyro_bias.getParam();
  for (int i = 0; i < gyro_bias.size(); ++i) out << gyro_bias[i];
  out << YAML::EndSeq;

  // noise / bias std devs
  out << YAML::Newline;
  out << YAML::Comment(
      "IMU noise and bias standard deviations (continuous-time, same value for x/y/z)");

  auto emit_vec3 = [&](const char* key, const Eigen::Vector3d& v) {
    out << YAML::Key << key << YAML::Value;
    out << YAML::Flow << YAML::BeginSeq << v.x() << v.y() << v.z()
        << YAML::EndSeq;
  };
  emit_vec3("accel_noise_std", calib.accel_noise_std);
  emit_vec3("gyro_noise_std",  calib.gyro_noise_std);
  emit_vec3("accel_bias_std",  calib.accel_bias_std);
  emit_vec3("gyro_bias_std",   calib.gyro_bias_std);

  // cam_time_offset_ns
  out << YAML::Newline;
  out << YAML::Comment("Camera-IMU time offset (nanoseconds)");
  out << YAML::Key << "cam_time_offset_ns" << YAML::Value
      << calib.cam_time_offset_ns;

  out << YAML::EndMap;

  std::ofstream file(path);
  if (!file.is_open())
    throw std::runtime_error("Cannot write calibration YAML: " + path);
  file << out.c_str() << "\n";
}

}  // namespace basalt
